version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./testdata/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./testdata/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=15d'
      - '--query.max-concurrency=50'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - influxdb
    networks:
      - prom_monitor
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    restart: always
    volumes:
      - ./testdata/influxdb/config:/etc/influxdb
      - ./testdata/influxdb/data:/var/lib/influxdb/data
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - TZ=Asia/Shanghai
      - INFLUXDB_DB=prometheus
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpwd
      - INFLUXDB_USER=prometheus
      - INFLUXDB_USER_PASSWORD=prometheuspwd
      - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf
    networks:
      - prom_monitor
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    volumes:
      - ./testdata/grafana/data:/var/lib/grafana
      - ./testdata/grafana/provisioning:/etc/grafana/provisioning
      - ./testdata/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - prom_monitor
  master:
    image: ${CONTAINER_NAME}
    container_name: locust_master
    hostname: locust_master
    restart: always
    volumes:
      - ./:/mnt/locust
    ports:
      - "${WEB_PROT}:8089"
      - "${MASTER_PROT}:5557"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - FLASK_APP_HOST=${FLASK_APP_HOST}
      - TZ=Asia/Shanghai
    networks:
      - prom_monitor
    # 如果不希望暴露公网,可以用局域网IP
    command: --master -f ${LOCUST_FILE_PATH} --master-bind-host=${LOCUST_MASTER_HOST}

  worker:
    image: ${CONTAINER_NAME}
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - FLASK_APP_HOST=${FLASK_APP_HOST}
      - TZ=Asia/Shanghai
    volumes:
      - ./:/mnt/locust
    networks:
      - prom_monitor
    command: --worker --master-host=${LOCUST_HOST} -f ${LOCUST_FILE_PATH}

  flask:
    image: ${FLASK_APP}
    container_name: flask
    restart: always
    ports:
      - "8000:8000"
    networks:
      - prom_monitor
    environment:
      - TZ=Asia/Shanghai
    command: [ "python", "/home/flask/testdata/testapi/myapp.py" ]

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - ${REAL_REDIS_PORT}:6379
    volumes:
      - ./testdata/redis/data:/data
      - ./testdata/redis/redis.conf:/etc/redis/redis.conf
      - ./testdata/redis/logs:/logs
    environment:
      - TZ=Asia/Shanghai
    restart: always
    command: [ "redis-server", "/etc/redis/redis.conf", "--appendonly yes", "--requirepass ${REDIS_PASSWORD}" ]


networks:
  prom_monitor:
    driver: bridge
